name: CI pipeline

on:
  push:
    branches:
      - workspace
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout our code
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - name: Run formatter
        run: cargo fmt -- --check

      - name: Run Linter
        run: cargo clippy --workspace --all-targets -- -D warnings

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout our code
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Run tests
        run: cargo test --workspace --all-targets

  build:
    needs: [lint, test]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout our code
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Build
        run: cargo build --workspace --all-targets
        # run: cargo build --workspace --all-targets --release

      # - name: Upload artifacts
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: encryptify-artifacts
      #     path: target/release
